// HAFDamageStatics.h
#pragma once

#include "CoreMinimal.h"
#include "GameplayEffectExecutionCalculation.h"
#include "GameplayEffectTypes.h"
#include "HAFGameplayTags.h"

struct HAFDamageStatics
{
	DECLARE_ATTRIBUTE_CAPTUREDEF(Armor);
	DECLARE_ATTRIBUTE_CAPTUREDEF(ArmorPenetration);
	DECLARE_ATTRIBUTE_CAPTUREDEF(BlockChance);
	DECLARE_ATTRIBUTE_CAPTUREDEF(CriticalHitChance);
	DECLARE_ATTRIBUTE_CAPTUREDEF(CriticalHitResistance);
	DECLARE_ATTRIBUTE_CAPTUREDEF(CriticalHitDamage);
	DECLARE_ATTRIBUTE_CAPTUREDEF(Agility);
	DECLARE_ATTRIBUTE_CAPTUREDEF(Flexibility);
	DECLARE_ATTRIBUTE_CAPTUREDEF(Purity);
	DECLARE_ATTRIBUTE_CAPTUREDEF(Corruptibility);
	DECLARE_ATTRIBUTE_CAPTUREDEF(Intuition);
	DECLARE_ATTRIBUTE_CAPTUREDEF(Vision);
	DECLARE_ATTRIBUTE_CAPTUREDEF(Speed);
	DECLARE_ATTRIBUTE_CAPTUREDEF(Charm);
	DECLARE_ATTRIBUTE_CAPTUREDEF(HealthRegeneration);
	DECLARE_ATTRIBUTE_CAPTUREDEF(ShieldRegeneration);
	DECLARE_ATTRIBUTE_CAPTUREDEF(StaminaRegeneration);
	DECLARE_ATTRIBUTE_CAPTUREDEF(MajixRegeneration);
	DECLARE_ATTRIBUTE_CAPTUREDEF(MaxHealth);
	DECLARE_ATTRIBUTE_CAPTUREDEF(MaxShield);
	DECLARE_ATTRIBUTE_CAPTUREDEF(MaxStamina);
	DECLARE_ATTRIBUTE_CAPTUREDEF(MaxMajix);
	DECLARE_ATTRIBUTE_CAPTUREDEF(IncomingDamage);
	DECLARE_ATTRIBUTE_CAPTUREDEF(Fireproof);
	DECLARE_ATTRIBUTE_CAPTUREDEF(Shockproof);
	DECLARE_ATTRIBUTE_CAPTUREDEF(ThermalRadiation);
	DECLARE_ATTRIBUTE_CAPTUREDEF(Invulnerability);
	DECLARE_ATTRIBUTE_CAPTUREDEF(HeartOfDarkness);
	DECLARE_ATTRIBUTE_CAPTUREDEF(ChaosIncorruptible);
	DECLARE_ATTRIBUTE_CAPTUREDEF(Immunity);
	DECLARE_ATTRIBUTE_CAPTUREDEF(Unstoppable);
	
	TMap<FGameplayTag, FGameplayEffectAttributeCaptureDefinition> TagsToCaptureDefs;
	
	HAFDamageStatics();
};