;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Attributes.Vital.Health",DevComment="Amount of Damage a Character Can Take Before Death")
+GameplayTagList=(Tag="Attributes.Vital.Majix",DevComment="The Amount of Summoning Power a Character has at Their Disposal to Cast Spells")
+GameplayTagList=(Tag="Attributes.Vital.MaxHealth",DevComment="The Absolute Maximum Amount of Healing One Can Do Before nThey Can\'t Be Healed Anymore")
+GameplayTagList=(Tag="Attributes.Vital.MaxMajix",DevComment="Any More Summoming Majix, and Their Power Could Threaten Their Soul for All Eternity. (For the Record, That Would Be Bad..)")
+GameplayTagList=(Tag="Attributes.Vital.MaxShield",DevComment="The Original Strength of a Character\'s Shield... No Further Fortification Will Have Any Effect onn It")
+GameplayTagList=(Tag="Attributes.Vital.MaxStamina",DevComment="As Physically Fit, Agile, and Dexterous as This Character Can Possibly Be... Primed to Dodge Every Attack That Comes Their Way")
+GameplayTagList=(Tag="Attributes.Vital.Shield",DevComment="The Amount of Damage a Character Can Take in Their Armor Before It\'s Destroyed, and All Incoming Damage Threatens Their Life")
+GameplayTagList=(Tag="Attributes.Vital.Stamina",DevComment="The Amount of Times a Character Can Doidge an Attack Before Fatigue Sets In, and Dodging is an Impossibility")
+GameplayTagList=(Tag="Message.HealthCrystal",DevComment="")
+GameplayTagList=(Tag="Message.HealthPotion",DevComment="")
+GameplayTagList=(Tag="Message.MajixCrystal",DevComment="")
+GameplayTagList=(Tag="Message.MajixPotion",DevComment="")
+GameplayTagList=(Tag="Message.ShieldCrystal",DevComment="")
+GameplayTagList=(Tag="Message.ShieldPotion",DevComment="")
+GameplayTagList=(Tag="Message.StaminaCrystal",DevComment="")
+GameplayTagList=(Tag="Message.StaminaPotion",DevComment="")

