;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Blueprints/GameplayTags/DataTables/DT_PrimaryAttributes.DT_PrimaryAttributes
+GameplayTagRedirects=(OldTagName="Message.HealthCrystal",NewTagName="Message.HealthKhristel")
+GameplayTagRedirects=(OldTagName="Message.MajixCrystal",NewTagName="Message.MajixKhristel")
+GameplayTagRedirects=(OldTagName="Message.ShieldCrystal",NewTagName="Message.ShieldKhristel")
+GameplayTagRedirects=(OldTagName="Message.StaminaCrystal",NewTagName="Message.StaminaKhristel")
+GameplayTagRedirects=(OldTagName="Message.HealthPotion",NewTagName="Message.HealthPoshun")
+GameplayTagRedirects=(OldTagName="Message.MajixPotion",NewTagName="Message.MajixPoshun")
+GameplayTagRedirects=(OldTagName="Message.ShieldPotion",NewTagName="Message.ShieldPoshun")
+GameplayTagRedirects=(OldTagName="Message.StaminaPotion",NewTagName="Message.StaminaPoshun")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Attributes.Vital.Health",DevComment="Amount of Damage a Character Can Take Before Death")
+GameplayTagList=(Tag="Attributes.Vital.Majix",DevComment="The Amount of Summoning Power a Character has at Their Disposal to Cast Spells")
+GameplayTagList=(Tag="Attributes.Vital.Shield",DevComment="The Amount of Damage a Character Can Take in Their Armor Before It\'s Destroyed, and All Incoming Damage Threatens Their Life")
+GameplayTagList=(Tag="Attributes.Vital.Stamina",DevComment="The Amount of Times a Character Can Doidge an Attack Before Fatigue Sets In, and Dodging is an Impossibility")
+GameplayTagList=(Tag="Message.HealthKhristel",DevComment="")
+GameplayTagList=(Tag="Message.HealthPoshun",DevComment="")
+GameplayTagList=(Tag="Message.MajixKhristel",DevComment="")
+GameplayTagList=(Tag="Message.MajixPoshun",DevComment="")
+GameplayTagList=(Tag="Message.ShieldKhristel",DevComment="")
+GameplayTagList=(Tag="Message.ShieldPoshun",DevComment="")
+GameplayTagList=(Tag="Message.StaminaKhristel",DevComment="")
+GameplayTagList=(Tag="Message.StaminaPoshun",DevComment="")
+GameplayTagList=(Tag="State.Charmed",DevComment="An Enemy AI becomes Charmed by how Charismatic you are!")
+GameplayTagList=(Tag="State.Fleeing",DevComment="An Enemy is running as far away from you as they can get! ")

