;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Blueprints/GameplayTags/DataTables/DT_PrimaryAttributes.DT_PrimaryAttributes
+GameplayTagRedirects=(OldTagName="Message.HealthCrystal",NewTagName="Message.HealthKhristel")
+GameplayTagRedirects=(OldTagName="Message.MajixCrystal",NewTagName="Message.MajixKhristel")
+GameplayTagRedirects=(OldTagName="Message.ShieldCrystal",NewTagName="Message.ShieldKhristel")
+GameplayTagRedirects=(OldTagName="Message.StaminaCrystal",NewTagName="Message.StaminaKhristel")
+GameplayTagRedirects=(OldTagName="Message.HealthPotion",NewTagName="Message.HealthPoshun")
+GameplayTagRedirects=(OldTagName="Message.MajixPotion",NewTagName="Message.MajixPoshun")
+GameplayTagRedirects=(OldTagName="Message.ShieldPotion",NewTagName="Message.ShieldPoshun")
+GameplayTagRedirects=(OldTagName="Message.StaminaPotion",NewTagName="Message.StaminaPoshun")
+GameplayTagRedirects=(OldTagName="State",NewTagName="EnemyState")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Abilities.FireBolt.Active",DevComment="Tag for when you have an active FireBolt in play")
+GameplayTagList=(Tag="Abilities.Passive.ListenForEvent",DevComment="When you just want to hear the damn event already....")
+GameplayTagList=(Tag="Attributes.Resistance.MeleeAttacks",DevComment="Resistance to Blunt Force Melee Attacks")
+GameplayTagList=(Tag="Attributes.Vital.Health",DevComment="Amount of Damage a Character Can Take Before Death")
+GameplayTagList=(Tag="Attributes.Vital.Majix",DevComment="The Amount of Summoning Power a Character has at Their Disposal to Cast Spells")
+GameplayTagList=(Tag="Attributes.Vital.Shield",DevComment="The Amount of Damage a Character Can Take in Their Armor Before It\'s Destroyed, and All Incoming Damage Threatens Their Life")
+GameplayTagList=(Tag="Attributes.Vital.Stamina",DevComment="The Amount of Times a Character Can Doidge an Attack Before Fatigue Sets In, and Dodging is an Impossibility")
+GameplayTagList=(Tag="Character.EnemyAI",DevComment="Identifies this Character as being one of the Enemy AI")
+GameplayTagList=(Tag="Character.Player",DevComment="Identifies this Character as belonging to a Player")
+GameplayTagList=(Tag="Cooldown.ChaosMajix.ArcaneShards",DevComment="Cooldown for Arcane Shards")
+GameplayTagList=(Tag="Cooldown.Fire.FireBlast",DevComment="When You Need to Coll Down Your Fire Blast")
+GameplayTagList=(Tag="Damage",DevComment="Event Tag for when Damage is Set by Caller")
+GameplayTagList=(Tag="Damage.Burn",DevComment="")
+GameplayTagList=(Tag="Damage.CorruptChaos",DevComment="")
+GameplayTagList=(Tag="Damage.Frostbite",DevComment="")
+GameplayTagList=(Tag="Damage.Paralysis",DevComment="")
+GameplayTagList=(Tag="Damage.Physical",DevComment="")
+GameplayTagList=(Tag="Damage.Physical.Gnarled",DevComment="")
+GameplayTagList=(Tag="Damage.Physical.Gnarledling",DevComment="")
+GameplayTagList=(Tag="Damage.Physical.Gunfire",DevComment="")
+GameplayTagList=(Tag="Damage.Physical.Guul",DevComment="")
+GameplayTagList=(Tag="Damage.Physical.Hellspawn",DevComment="Encompassing all the Hellspawn")
+GameplayTagList=(Tag="Damage.Physical.Hellspawn.Bloodspawn",DevComment="Only Bloodspawn")
+GameplayTagList=(Tag="Damage.Physical.Hellspawn.Netherspawn",DevComment="Only Netherspawn")
+GameplayTagList=(Tag="Damage.Physical.StormAssassin",DevComment="")
+GameplayTagList=(Tag="Damage.Physical.Thrope",DevComment="")
+GameplayTagList=(Tag="Damage.Poison",DevComment="")
+GameplayTagList=(Tag="Damage.PureOrder",DevComment="")
+GameplayTagList=(Tag="Damage.Shock",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="EnemyState",DevComment="An Enemy AI becomes Charmed by how Charismatic you are!")
+GameplayTagList=(Tag="Event.Montage.ArcaneShards",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Attack.Melee",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Electrocute",DevComment="Share your spark!")
+GameplayTagList=(Tag="Event.Montage.FireBolt",DevComment="Because if you\'re going to Throw a FireBolt, at least Do It in Style....")
+GameplayTagList=(Tag="GameplayCue.ArcaneShardsBurst",DevComment="ArcaneShards Ga,meplay Cue Notify Burst")
+GameplayTagList=(Tag="GameplayCue.MeleeImpact",DevComment="Inpact Sights and Sounds for Melee Attacks")
+GameplayTagList=(Tag="GameplayCue.ShockBurst",DevComment="When Cueing up ShockBurst")
+GameplayTagList=(Tag="GameplayCue.ShockLoop",DevComment="When your shock is caught in a loop")
+GameplayTagList=(Tag="GameplayCue.ShockloopAsStatic",DevComment="Testing out Gameplay Loop As Static")
+GameplayTagList=(Tag="GameplayState.PvE",DevComment="Player vs Environment")
+GameplayTagList=(Tag="GameplayState.PvP",DevComment="Player vs Player")
+GameplayTagList=(Tag="InputTag.Passive.1",DevComment="")
+GameplayTagList=(Tag="InputTag.Passive.2",DevComment="")
+GameplayTagList=(Tag="Message.HealthKhristel",DevComment="")
+GameplayTagList=(Tag="Message.HealthPoshun",DevComment="")
+GameplayTagList=(Tag="Message.MajixKhristel",DevComment="")
+GameplayTagList=(Tag="Message.MajixPoshun",DevComment="")
+GameplayTagList=(Tag="Message.ShieldKhristel",DevComment="")
+GameplayTagList=(Tag="Message.ShieldPoshun",DevComment="")
+GameplayTagList=(Tag="Message.StaminaKhristel",DevComment="")
+GameplayTagList=(Tag="Message.StaminaPoshun",DevComment="")
+GameplayTagList=(Tag="Montage.Attack.BothHands",DevComment="When an Enemy Attacks with Both Hands")
+GameplayTagList=(Tag="Montage.Attack.HandsAndFeet",DevComment="When an Enemy Attacks With Their Hands And Feet")
+GameplayTagList=(Tag="Montage.Attack.RightFoot",DevComment="When an Enemy Attacks With Their Right Foot")
+GameplayTagList=(Tag="State.Charmed",DevComment="An Enemy AI becomes Charmed by how Charismatic you are!")
+GameplayTagList=(Tag="State.Combat",DevComment="When You\'re Fighting for your Life.... or just a little bit of Health... either works")
+GameplayTagList=(Tag="State.Fleeing",DevComment="An Enemy is running as far away from you as they can get! ")
+GameplayTagList=(Tag="State.Resting",DevComment="Take a break and chill out, man....")

